# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(348, 261)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tendn = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tendn.setGeometry(QtCore.QRect(20, 10, 271, 41))
        self.tendn.setStyleSheet("font: 75 20pt \"Times New Roman\";")
        self.tendn.setObjectName("tendn")
        self.matkhau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.matkhau.setGeometry(QtCore.QRect(20, 70, 271, 41))
        self.matkhau.setStyleSheet("font: 75 20pt \"Times New Roman\";")
        self.matkhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.matkhau.setObjectName("matkhau")
        self.run = QtWidgets.QPushButton(parent=self.centralwidget)
        self.run.setGeometry(QtCore.QRect(140, 150, 181, 51))
        self.run.setStyleSheet("font: 75 20pt \"Times New Roman\";")
        self.run.setObjectName("run")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 348, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tendn.setPlaceholderText(_translate("MainWindow", "Nhập tên đăng nhập"))
        self.matkhau.setPlaceholderText(_translate("MainWindow", "Nhập vào password"))
        self.run.setText(_translate("MainWindow", "Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
