# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 628)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 700, 500))
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(120, 510, 131, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Button_start.setFont(font)
        self.Button_start.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Button_start.setObjectName("Button_start")
        self.Button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop.setGeometry(QtCore.QRect(500, 510, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Button_stop.setFont(font)
        self.Button_stop.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Button_stop.setObjectName("Button_stop")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(300, 510, 151, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select.setFont(font)
        self.select.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.select.setObjectName("select")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPh_n_Lo_i = QtWidgets.QAction(MainWindow)
        self.actionPh_n_Lo_i.setObjectName("actionPh_n_Lo_i")
        self.actionKho = QtWidgets.QAction(MainWindow)
        self.actionKho.setObjectName("actionKho")
        self.actionTr_i_C_y = QtWidgets.QAction(MainWindow)
        self.actionTr_i_C_y.setObjectName("actionTr_i_C_y")
        self.Logout = QtWidgets.QAction(MainWindow)
        self.Logout.setObjectName("Logout")
        self.menuMenu.addAction(self.actionPh_n_Lo_i)
        self.menuMenu.addAction(self.actionKho)
        self.menuMenu.addAction(self.actionTr_i_C_y)
        self.menuMenu.addAction(self.Logout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_start.setText(_translate("MainWindow", "Phân Loại"))
        self.Button_stop.setText(_translate("MainWindow", "Thêm vào kho"))
        self.select.setText(_translate("MainWindow", "Thêm trái cây"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionPh_n_Lo_i.setText(_translate("MainWindow", "Phân Loại"))
        self.actionKho.setText(_translate("MainWindow", "Kho"))
        self.actionTr_i_C_y.setText(_translate("MainWindow", "Trái Cây"))
        self.Logout.setText(_translate("MainWindow", "Đăng Xuất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
