# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kho.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class kho_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_start = QtWidgets.QPushButton(self.centralwidget)
        self.Button_start.setGeometry(QtCore.QRect(320, 190, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_start.setFont(font)
        self.Button_start.setObjectName("Button_start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.phanloai = QtWidgets.QAction(MainWindow)
        self.phanloai.setObjectName("phanloai")
        self.kho = QtWidgets.QAction(MainWindow)
        self.kho.setObjectName("kho")
        self.traicay = QtWidgets.QAction(MainWindow)
        self.traicay.setObjectName("traicay")
        self.logout = QtWidgets.QAction(MainWindow)
        self.logout.setObjectName("logout")
        self.menuMenu.addAction(self.phanloai)
        self.menuMenu.addAction(self.kho)
        self.menuMenu.addAction(self.traicay)
        self.menuMenu.addAction(self.logout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_start.setText(_translate("MainWindow", "kho"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.phanloai.setText(_translate("MainWindow", "Phân Loại"))
        self.kho.setText(_translate("MainWindow", "Kho"))
        self.traicay.setText(_translate("MainWindow", "Trái Cây"))
        self.logout.setText(_translate("MainWindow", "Đăng Xuất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
