# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kho.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class kho_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loaddt = QtWidgets.QPushButton(self.centralwidget)
        self.loaddt.setGeometry(QtCore.QRect(20, 450, 161, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loaddt.setFont(font)
        self.loaddt.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.loaddt.setObjectName("loaddt")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 811, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.update = QtWidgets.QPushButton(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(340, 450, 161, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.update.setFont(font)
        self.update.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.update.setObjectName("update")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(620, 450, 161, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";")
        self.delete_2.setObjectName("delete_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.phanloai = QtWidgets.QAction(MainWindow)
        self.phanloai.setObjectName("phanloai")
        self.kho = QtWidgets.QAction(MainWindow)
        self.kho.setObjectName("kho")
        self.traicay = QtWidgets.QAction(MainWindow)
        self.traicay.setObjectName("traicay")
        self.logout = QtWidgets.QAction(MainWindow)
        self.logout.setObjectName("logout")
        self.menuMenu.addAction(self.phanloai)
        self.menuMenu.addAction(self.kho)
        self.menuMenu.addAction(self.traicay)
        self.menuMenu.addAction(self.logout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loaddt.setText(_translate("MainWindow", "Load data"))
        self.update.setText(_translate("MainWindow", "Update"))
        self.delete_2.setText(_translate("MainWindow", "DELETE"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.phanloai.setText(_translate("MainWindow", "Phân Loại"))
        self.kho.setText(_translate("MainWindow", "Kho"))
        self.traicay.setText(_translate("MainWindow", "Trái Cây"))
        self.logout.setText(_translate("MainWindow", "Đăng Xuất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
